[package]
name = "netherrack"
version = "0.0.2-pre"
authors = ["Cruz Julian Bishop <cruzjbishop@gmail.com>"]
description = "A Minecraft server programmed in Rust"

repository = "https://github.com/Techern/Netherrack"
documentation = "http://techern.github.io/Netherrack"
readme = "README.md"
keywords = ["Minecraft", "Server"]
license = "MIT OR Apache-2.0"

[dependencies]
semver = "0.1.20"
log = "0.3.1"
integral_square_root = "1.0.0"
chrono = "0.2.15"
uuid = "0.1.17"
varint = "0.2.0"
bit_utils = "0.1.0"
rustc-serialize = "0.3.16"
io_operations = "0.1.0"
lazy_static = "0.1.14"

[lib]
name = "netherrack"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true
plugin = false
harness = true

[[bin]]
name = "netherrack_executable"
path = "src/main.rs"
test = false
doctest = false
bench = false
doc = false
plugin = false
harness = false
